import Header from "@/components/header";
import { StoreProvider } from "@/store/StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Layout from "@/helper/LayoutProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className="scrollbar-hide">
        <body className={inter.className}>
          <Toaster position="bottom-center" />
          <Layout>{children}</Layout>
          <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
        </body>
      </html>
    </StoreProvider>
  );
}
